-- AlterTable
ALTER TABLE `taskhistory` ADD COLUMN `monthPerformed` INTEGER NOT NULL DEFAULT 8,
    ADD COLUMN `status` ENUM('PENDING', 'COMPLETED', 'SKIPPED', 'CANCELLED') NOT NULL DEFAULT 'COMPLETED',
    ADD COLUMN `yearPerformed` INTEGER NOT NULL DEFAULT 2024;
